include ./yoake.conf

# Font
font_family      JetBrainsMono Nerd Font
font_size        11.0
bold_font        auto
italic_font      auto
bold_italic_font auto
modify_font cell_height 110%

# Cursor — beam with trail
cursor_shape               beam
cursor_shape_unfocused     unchanged
cursor_beam_thickness      8
cursor_blink_interval      0.5
cursor_stop_blinking_after 0
cursor_trail               1
cursor_trail_decay         0.1 0.4
cursor_trail_start_threshold 2

# Mouse
mouse_hide_wait 2.0

# URLs
url_color #e9cdb0
url_style dotted

# Window
window_padding_width    8 25 25 25
background_opacity         0.65
dynamic_background_opacity yes
confirm_os_window_close    0
hide_window_decorations    yes

# Tab bar — hidden when only one tab, minimal otherwise
tab_bar_style         powerline
tab_powerline_style   round
tab_bar_min_tabs      2
tab_bar_edge          bottom
active_tab_font_style bold
inactive_tab_font_style normal

# Scrollback
scrollback_lines 10000

# Bell
enable_audio_bell no
visual_bell_duration 0.0
