#!/usr/bin/env bash
# wal-sync.sh — drop-in replacement for pywal-spicetify (AUR build was failing).
# Reads ~/.cache/wal/colors.sh and writes a [wal] color scheme into the
# Comfy theme, then runs `spicetify apply`.
#
# Usage:
#   wal -i /path/to/wallpaper.png
#   ~/Documents/GitHub/linux-rice/spicetify/wal-sync.sh
#
# Or wire it into your wallpaper changer (e.g. waypaper):
#   post_command = wal -i $wallpaper && bash ~/Documents/GitHub/linux-rice/spicetify/wal-sync.sh
#
# Switch active scheme:
#   spicetify config color_scheme wal    # follow wallpaper
#   spicetify config color_scheme yoake  # fixed rice palette
#   spicetify apply

set -euo pipefail

WAL_COLORS="${HOME}/.cache/wal/colors.sh"
THEME_DIR="${HOME}/.config/spicetify/Themes/Comfy"
COLOR_INI="${THEME_DIR}/color.ini"

[[ -f "$WAL_COLORS" ]] || { echo "wal-sync: $WAL_COLORS not found — run 'wal -i <wallpaper>' first" >&2; exit 1; }
[[ -f "$COLOR_INI" ]] || { echo "wal-sync: $COLOR_INI not found — Comfy not installed?" >&2; exit 1; }

# pywal's colors.sh appends to $FZF_DEFAULT_OPTS, which fails under set -u
# if it's unset. Relax nounset just for the source.
set +u
# shellcheck source=/dev/null
source "$WAL_COLORS"
set -u

strip() { echo "${1#\#}"; }

bg=$(strip "$background");  fg=$(strip "$foreground")
c0=$(strip "$color0");      c1=$(strip "$color1")
c2=$(strip "$color2");      c4=$(strip "$color4")
c5=$(strip "$color5");      c7=$(strip "$color7")
c8=$(strip "$color8");      c12=$(strip "$color12")

# Remove any existing [wal] section, then append a fresh one.
awk 'BEGIN{skip=0} /^\[wal\]/{skip=1; next} /^\[/{skip=0} skip==0{print}' "$COLOR_INI" > "${COLOR_INI}.tmp"
mv "${COLOR_INI}.tmp" "$COLOR_INI"

cat >> "$COLOR_INI" <<EOF

[wal]
; generated by wal-sync.sh from ~/.cache/wal/colors.sh
text               = ${fg}
subtext            = ${c7}
main               = ${bg}
main-elevated      = ${c8}
main-transition    = ${c0}
highlight          = ${c8}
highlight-elevated = ${c0}
sidebar            = ${c0}
player             = ${c0}
card               = ${c8}
shadow             = ${c0}
selected-row       = ${fg}
button             = ${c4}
button-active      = ${c12}
button-disabled    = ${c8}
tab-active         = ${c8}
notification       = ${c4}
notification-error = ${c1}
misc               = ${c5}
play-button        = ${c4}
play-button-active = ${c12}
progress-fg        = ${c4}
progress-bg        = ${c8}
heart              = ${c1}
pagelink-active    = ${c12}
radio-btn-active   = ${c4}
EOF

spicetify config color_scheme wal >/dev/null
spicetify apply >/dev/null
echo "wal-sync: applied [wal] scheme to Comfy"
